# Generated by Django 3.0 on 2022-07-15 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220715_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(default=uuid.UUID('f066d9ba-76e3-41da-95a7-593d09d8681f'), max_length=2255, unique=True),
        ),
    ]
