# Generated by Django 3.0 on 2022-07-15 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220716_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(default=uuid.UUID('9d9af901-9139-462e-8fd2-a9c9c608e466'), max_length=2255, unique=True),
        ),
    ]
