# Generated by Django 3.0 on 2022-07-15 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220716_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(default=uuid.UUID('d626e2a1-ee1b-4d6d-9513-e82932ec1d45'), max_length=2255, unique=True),
        ),
    ]
